<?xml version = '1.0' encoding = 'utf-8'?>
<!--Generated by Oracle BI Publisher 10.1.3.4.1-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="30.6pt" margin-right="30.6pt" page-height="841.95pt" page-width="595.35pt" margin-top="36.0pt" margin-bottom="36.0pt">
               <fo:region-before region-name="region-header" extent="0.0pt"/>
               <fo:region-body region-name="region-body" margin-top="0.0pt" margin-bottom="0.0pt"/>
               <fo:region-after region-name="region-footer" extent="0.0pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(595.35)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(841.95)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header">
               <fo:block xdofo:alt="background" start-indent="5.4pt" height="0.0pt">
                  <fo:instream-foreign-object width="{xdoxslt:ifelse($_XDOOUTPUTFORMAT='application/pdf','0.001','412.4')}pt" height="{xdoxslt:ifelse($_XDOOUTPUTFORMAT='application/pdf','11.0','247.45')}pt" xdofo:alt="background" content-type="image/svg+xml" xdofo:w="595.35pt" xdofo:h="841.95pt">
                     <svg xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xlink="http://www.w3.org/1999/xlink" width="595.35pt" height="841.95pt" viewBox="0 0 595.35pt 841.95pt" xdofo:alt="background">
                        <g xdofo:z-order="-1000" transform="translate({xdoxslt:ifelse(xdoxslt:is_bidi_locale($_XDOLOCALE), $_MR - $_PW, -$_ML)} {-$_HY}) translate({$_ML + ($_PW - $_ML - $_MR - number(412.4)) div 2} {$_MT + ($_PH - $_MT - $_MB - number(247.45)) div 2})">
                           <g xdofo:shape-id="136">
                              <g stroke="none" stroke-width="0.75" stroke-linejoin="round" fill="white" transform="rotate(315.0 206.2 123.725)" opacity="0.5">
                                 <text x="0.0" font-size="247" xdofo:horizontal-scaling="66.67%" y="155.76382446289062" font-family="Calibri" xdofo:w="-412.3999938964844" xdofo:horizontal-align="center">DRAFT</text>
                              </g>
                           </g>
                        </g>
                     </svg>
                  </fo:instream-foreign-object>
               </fo:block>
               <fo:block xdofo:tab-stops="center:234.0pt:space right:468.0pt:space" xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="10.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <xsl:call-template name="MyHeader">
                     <xsl:with-param name="_XDOFOPOS" select="$_XDOFOPOS"/>
                     <xsl:with-param name="_XDOFOPOS2" select="$_XDOFOPOS2"/>
                     <xsl:with-param name="_XDOFOOSTOTAL" select="$_XDOFOOSTOTAL"/>
                     <xsl:with-param name="_XDOFOTOTAL" select="$_XDOFOTOTAL"/>
                     <xsl:with-param name="_SECTION_NAME" select="$_SECTION_NAME"/>
                  </xsl:call-template>
               </fo:block>
            </fo:static-content>
            <fo:static-content flow-name="region-footer"/>
            <fo:flow flow-name="region-body">
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="12.716001pt" font-family="Arial" font-size="11.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve">
                  <fo:table start-indent="9.55pt" style-id="ts11" style-name="Normal Table" xdofo:table-summary="Template Table 4" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="504.35pt"/>
                     <fo:table-body>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_CLAUSE_TYPE)"/>
                        <xsl:for-each select=".//G_CLAUSE_TYPE" xdofo:ctx="3">
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <fo:table-row xdofo:repeat="R">
                              <fo:table-cell padding-end="0.0pt" padding-bottom="0.0pt" padding-start="0.0pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" background-color="#ffffff">
                                 <fo:block xdofo:xliff-note="GROUP:G_PRODUCTS, PRODUCTS" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline white-space-collapse="false" font-weight="bold" height="14.0pt" font-family="Cambria" text-decoration="underline" font-size="14.0pt">
                                       <xsl:value-of select=".//CLAUSE_TYPE" xdofo:field-name="CLAUSE_TYPE"/>
                                    </fo:inline>
                                 </fo:block>
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.25pt" end-indent="0.0pt" padding-top="0.25pt">
                                    <fo:table start-indent="0.25pt" style-id="ts11" style-name="Normal Table" xdofo:table-summary="Template Table 3" xdofo:row-header-count="0">
                                       <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                                       <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                                       <fo:table-column column-width="499.85pt"/>
                                       <fo:table-body>
                                          <fo:table-row>
                                             <fo:table-cell vertical-align="top" border-start-color="#000000" background-color="#ffffff" height="0.0pt" padding-start="0.0pt" border-start-style="solid" border-start-width="0.5pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-end="0.0pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-color="#000000" border-end-style="solid" padding-bottom="0.0pt" border-end-width="0.5pt">
                                                <fo:block xdofo:xliff-note="G_pr_code" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                                   <fo:inline height="11.0pt" white-space-collapse="false" font-size="11.0pt" color="#000000" font-family="Cambria">
                                                      <xsl:value-of select=".//CLS_WORDING" xdofo:field-name="CLS_WORDING"/>
                                                   </fo:inline>
                                                </fo:block>
                                                <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.25pt" end-indent="0.0pt" padding-top="0.25pt">
                                                   <fo:table start-indent="0.25pt" style-id="ts11" style-name="Normal Table" xdofo:table-summary="Template Table 2" xdofo:row-header-count="0">
                                                      <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                                                      <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                                                      <fo:table-column column-width="499.85pt"/>
                                                      <fo:table-body>
                                                         <fo:table-row>
                                                            <fo:table-cell vertical-align="top" border-start-color="#000000" background-color="#ffffff" height="0.0pt" padding-start="0.0pt" border-start-style="solid" border-start-width="0.5pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-end="0.0pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-color="#000000" border-end-style="solid" padding-bottom="0.0pt" border-end-width="0.5pt">
                                                               <fo:block xdofo:xliff-note="G_pr_desc" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                                                  <fo:inline height="11.0pt" white-space-collapse="false" font-size="11.0pt" color="#000000" font-family="Cambria" font-weight="bold">
                                                                     <xsl:for-each select=".//G_CLAUSE_TYPE" xdofo:ctx="4"/>
                                                                  </fo:inline>
                                                               </fo:block>
                                                            </fo:table-cell>
                                                         </fo:table-row>
                                                      </fo:table-body>
                                                   </fo:table>
                                                </fo:block>
                                                <fo:block/>
                                             </fo:table-cell>
                                          </fo:table-row>
                                       </fo:table-body>
                                    </fo:table>
                                 </fo:block>
                                 <fo:block xdofo:xliff-note="END G_1, END G_PRODUCTS" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline xml:space="preserve" height="11.0pt" white-space-collapse="false" font-size="11.0pt" color="#000000" font-family="Cambria" font-weight="bold"> </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                        </xsl:for-each>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline height="12.716001pt" font-family="Arial" white-space-collapse="false" font-size="11.0pt"> </fo:inline>
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
   <xsl:template name="MyHeader">
      <xsl:param name="_XDOFOPOS"/>
      <xsl:param name="_XDOFOPOS2"/>
      <xsl:param name="_XDOFOOSTOTAL"/>
      <xsl:param name="_XDOFOTOTAL"/>
      <xsl:param name="_SECTION_NAME"/>
      <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve">
         <fo:table start-indent="5.4pt" style-id="ts11" style-name="Normal Table" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
            <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
            <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
            <fo:table-column column-width="339.75pt"/>
            <fo:table-column column-width="123.75pt"/>
            <fo:table-body>
               <fo:table-row>
                  <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                     <fo:block xdofo:xliff-note="ORGANIZATION" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                        <fo:inline height="10.0pt" font-family="Cambria" white-space-collapse="false" font-size="10.0pt" font-weight="bold">
                           <xsl:value-of select=".//ORGANIZATION" xdofo:field-name="ORGANIZATION"/>
                        </fo:inline>
                     </fo:block>
                  </fo:table-cell>
                  <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" number-rows-spanned="2">
                     <fo:block height="10.0pt"/>
                  </fo:table-cell>
               </fo:table-row>
               <fo:table-row>
                  <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                     <fo:block xdofo:xliff-note="ORG_PHY_ADDRS" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                        <fo:inline height="10.0pt" font-family="Cambria" white-space-collapse="false" font-size="10.0pt">
                           <xsl:value-of select=".//ORG_PHY_ADDRS" xdofo:field-name="ORG_PHY_ADDRS"/>
                        </fo:inline>
                     </fo:block>
                  </fo:table-cell>
               </fo:table-row>
               <fo:table-row>
                  <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                     <fo:block xdofo:xliff-note="TELEPHONE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                        <fo:inline height="10.0pt" font-family="Cambria" white-space-collapse="false" font-size="10.0pt">
                           <xsl:value-of select=".//TELEPHONE" xdofo:field-name="TELEPHONE"/>
                        </fo:inline>
                     </fo:block>
                  </fo:table-cell>
                  <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" number-rows-spanned="2">
                     <fo:block height="10.0pt"/>
                  </fo:table-cell>
               </fo:table-row>
               <fo:table-row>
                  <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                     <fo:block xdofo:xliff-note="EMAIL" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                        <fo:inline height="10.0pt" font-family="Cambria" white-space-collapse="false" font-size="10.0pt">
                           <xsl:value-of select=".//EMAIL" xdofo:field-name="EMAIL"/>
                        </fo:inline>
                     </fo:block>
                  </fo:table-cell>
               </fo:table-row>
            </fo:table-body>
         </fo:table>
      </fo:block>
   </xsl:template>
</xsl:stylesheet>
